2024-08-26 14:10:43,530 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 15:45:45,174 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 17:51:41,209 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 17:51:54,662 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 17:54:32,350 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 17:54:45,194 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 17:57:34,569 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:04:44,061 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:06:04,653 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:07:28,095 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 18:13:54,081 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:19:50,022 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 18:20:49,669 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:67]
2024-08-26 18:23:01,248 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:27:06,288 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:30:44,814 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'e27a5a65-e0b2-4a77-aba3-ea166bf41697', 'user_id': 'user2', 'chatDate': datetime.datetime(2024, 8, 26, 9, 30, 44, 800491), 'topic_id': '1', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-26 18:30:44,816 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-26 18:32:43,201 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'd70a6b74-d863-487c-88e2-21752dceaa83', 'user_id': 'user2', 'chatDate': datetime.datetime(2024, 8, 26, 9, 32, 43, 186351), 'topic_id': '1', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-26 18:32:43,204 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-26 18:51:11,238 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 18:53:20,882 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'ad998dc2-3a45-4070-a206-92995c4081b3', 'user_id': 'user2', 'chatDate': datetime.datetime(2024, 8, 26, 9, 53, 20, 852050), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 5, 'grammar': 6, 'vocabulary': 4, 'content': 7, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-26 18:53:20,884 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-26 18:54:17,195 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 19:13:10,188 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-26 19:13:36,866 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:69]
2024-08-26 19:13:44,167 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:69]
2024-08-26 19:14:47,326 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:69]
2024-08-27 08:33:36,582 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-27 09:36:54,966 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:63]
2024-08-27 09:37:13,992 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:63]
2024-08-27 09:39:30,160 INFO: AIChatTest saved successfully [in C:\project\sesac\aiFriend\app\ai_chat.py:78]
2024-08-27 09:42:27,212 INFO: AIChatTest saved successfully [in C:\project\sesac\aiFriend\app\ai_chat.py:78]
2024-08-27 11:49:06,377 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:63]
2024-08-27 12:01:08,748 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:47]
2024-08-27 12:01:27,123 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 12:05:08,171 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:47]
2024-08-27 12:05:53,521 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:47]
2024-08-27 12:11:10,667 WARNING: Failed login attempt for user begite [in C:\project\sesac\aiFriend\app\auth\routes.py:76]
2024-08-27 12:11:18,235 INFO: User logged in: begite [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 12:12:13,104 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 12:20:31,007 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 12:55:56,196 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 13:04:32,313 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:47]
2024-08-27 13:04:51,279 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 13:05:16,401 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:06:15,687 INFO: User logged in: user4 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:07:27,884 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:08:18,373 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:09:13,230 INFO: User logged in: user1 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:09:23,919 INFO: User logged in: user2 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:12:05,033 INFO: AIChatTest saved successfully [in C:\project\sesac\aiFriend\app\ai_chat.py:78]
2024-08-27 15:17:39,303 INFO: User logged in: user3 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:25:35,580 INFO: User logged in: user4 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
2024-08-27 15:28:28,677 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:47]
2024-08-27 15:31:25,471 INFO: User logged in: user5 [in C:\project\sesac\aiFriend\app\auth\routes.py:72]
