2024-08-29 15:32:33,470 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-29 17:38:46,849 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-29 21:51:01,261 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '90cdcedc-f89c-4b80-8749-c4225bf799b4', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 29, 12, 51, 1, 243265), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-29 21:51:01,261 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-30 09:12:10,785 WARNING: Failed login attempt for user user2 [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-30 09:12:18,047 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
