2024-08-28 15:01:04,891 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '3fcac094-2273-47ed-88b9-53dfa9552c12', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 28, 6, 1, 4, 881588), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 6, 'grammar': 5, 'vocabulary': 7, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-28 15:01:04,891 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-28 15:20:47,825 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:22:47,105 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:23:07,173 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 15:25:03,272 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:26:40,073 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:26:53,685 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:27:46,311 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:27:53,582 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 15:28:20,645 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:32:18,460 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:32:18,491 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:32:18,497 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:32:39,629 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:33:00,440 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:33:53,932 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'cbdbc2ef-c4a6-4707-905c-e8c5cdc77468', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 28, 7, 33, 53, 917465), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 4, 'grammar': 5, 'vocabulary': 6, 'content': 7, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-28 16:33:53,932 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-28 16:36:05,884 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '0782b224-0f4c-481c-b9ae-b4a096c7398f', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 28, 7, 36, 5, 872521), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 6, 'grammar': 7, 'vocabulary': 8, 'content': 9, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-28 16:36:05,884 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-28 16:36:55,069 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '40c79714-bd88-4c9c-8478-4acbacb2675d', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 28, 7, 36, 55, 58041), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 6, 'grammar': 7, 'vocabulary': 8, 'content': 5, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-28 16:36:55,069 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-28 16:38:31,977 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:39:41,460 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:40:21,708 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:41:10,906 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:42:39,290 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:46:51,702 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:47:23,633 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:47:28,120 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:48:22,899 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 16:49:06,833 INFO: User logged in: user1 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:49:23,207 WARNING: Failed login attempt for user user3 [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-28 16:49:38,683 WARNING: Failed login attempt for user user3 [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-28 16:49:55,591 WARNING: Failed login attempt for user user3 [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-28 16:50:05,621 WARNING: Failed login attempt for user begite [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-28 16:50:21,384 WARNING: Failed login attempt for user begite [in /home/star/project/AiFriend/app/auth/routes.py:76]
2024-08-28 16:50:32,600 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:51:38,648 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:52:13,344 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '318c5739-0d58-468a-9a36-4f31379501ef', 'user_id': '6856f521-3d73-4c18-a8c8-96185a500691', 'chatDate': datetime.datetime(2024, 8, 28, 7, 52, 13, 319321), 'topic_id': '8196329c-5a7d-4371-aa96-a2a3ef6f52a3', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /home/star/project/AiFriend/app/ai_chat.py:82]
2024-08-28 16:52:13,344 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:138]
2024-08-28 16:52:41,466 INFO: User logged in: user1 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:52:56,213 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:53:22,386 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 16:54:05,372 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:47]
2024-08-28 17:35:14,274 INFO: User logged in: user1 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-28 19:36:04,088 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-29 11:24:38,400 INFO: User logged in: user2 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-29 11:32:00,914 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-29 11:33:06,136 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
2024-08-29 14:52:37,610 INFO: User logged in: abc1234 [in /home/star/project/AiFriend/app/auth/routes.py:72]
