2024-08-12 10:23:13,496 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:10:31,407 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:10:31,524 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:11:22,170 ERROR: Failed to save AI test result: (pymysql.err.OperationalError) (1698, "Access denied for user 'root'@'localhost'")
(Background on this error at: https://sqlalche.me/e/20/e3q8) [in /home/star/project/AiFriend/app/ai_chat.py:76]
2024-08-12 11:11:22,170 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in /home/star/project/AiFriend/app/ai_chat.py:132]
2024-08-12 11:12:33,039 ERROR: Failed to parse AI response: Expecting ',' delimiter: line 6 column 34 (char 94) [in /home/star/project/AiFriend/app/ai_chat.py:113]
2024-08-12 11:12:33,039 ERROR: Error: An error occurred while parsing the AI response. [in /home/star/project/AiFriend/app/ai_chat.py:192]
2024-08-12 11:12:55,573 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:14:54,914 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:14:55,018 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 11:41:20,922 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 12:48:56,535 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-12 12:48:56,663 INFO: App startup [in /home/star/project/AiFriend/app/__init__.py:51]
2024-08-13 10:49:33,341 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-13 10:51:57,680 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
