2024-08-23 17:41:52,432 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': '4a539bc5-15d8-42ee-ab62-8494944dd797', 'user_id': 'test_user', 'chatDate': datetime.datetime(2024, 8, 23, 8, 41, 52, 376244), 'topic_id': '1', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-23 17:41:52,452 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-23 17:44:28,389 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 21:20:42,632 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 22:09:01,098 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 22:19:47,669 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-24 12:01:40,729 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-24 12:09:07,559 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:54]
2024-08-24 12:46:29,716 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:54]
2024-08-24 12:46:59,571 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:54]
2024-08-24 12:48:15,059 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:54]
